// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVExgX-DrWh5wy6fj4gXWnbA0NOZ2DyYg',
    appId: '1:753447301555:android:5663da2eccfc1433861bc6',
    messagingSenderId: '753447301555',
    projectId: 'my-song-22d08',
    storageBucket: 'my-song-22d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7RjPKEbT57GQRJD9mPBnokx72nGHxuZw',
    appId: '1:753447301555:ios:df6e0d8c015479a3861bc6',
    messagingSenderId: '753447301555',
    projectId: 'my-song-22d08',
    storageBucket: 'my-song-22d08.appspot.com',
    iosClientId: '753447301555-k3efjuqi8j6jfmn37mm0sp8neg8nq2hn.apps.googleusercontent.com',
    iosBundleId: 'com.chagil.mysongapp',
  );
}
