// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5SEU-hlsyYKU_9nVDiix-8fuuzEpKg6Q',
    appId: '1:645557053341:android:66cca00e71af35d9853174',
    messagingSenderId: '645557053341',
    projectId: 'audio-webview',
    storageBucket: 'audio-webview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9_SeQ1Z-8zyrYYhDjIxUDEDRd-Boiblk',
    appId: '1:645557053341:ios:a06fc43e04608151853174',
    messagingSenderId: '645557053341',
    projectId: 'audio-webview',
    storageBucket: 'audio-webview.appspot.com',
    iosClientId: '645557053341-s72thhuhgpd5it5g4e72aot7p2rkl7c0.apps.googleusercontent.com',
    iosBundleId: 'com.chagil.webview',
  );
}
